### ISSUE TITLE
Node Validation Fails During task configure Due to Port 50000 Not Being Open

### ISSUE THREAD

**Issue by dalekurt** [onedr0p/cluster-template#1563]
Has anyone encountered this issue? I encountered an issue while running the task configure command in the project. The configuration process fails due to a validation error related to node accessibility on port 50000.

```
task configure
task: Task "sops:age-keygen" is up to date
task: Task "workstation:venv" is up to date
task: [workstation:direnv] direnv allow .
Any conflicting config in the kubernetes directory will be overwritten... continue? [y/N]: y
task: [.template] /Users/dalekurt/Workspaces/cluster-template/.venv/bin/makejinja
Load data '/Users/dalekurt/Workspaces/cluster-template/config.yaml'
Traceback (most recent call last):
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/bin/makejinja", line 8, in <module>
    sys.exit(makejinja_cli())
             ^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/typed_settings/cli_click.py", line 248, in new_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/makejinja/cli.py", line 37, in makejinja_cli
    makejinja(config)
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/makejinja/app.py", line 60, in makejinja
    plugins.append(load_plugin(plugin_name, env, data, config))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/.venv/lib/python3.12/site-packages/makejinja/app.py", line 351, in load_plugin
    plugin = cls(**params)
             ^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/bootstrap/scripts/plugin.py", line 63, in __init__
    validation.validate(data)
  File "/Users/dalekurt/Workspaces/cluster-template/bootstrap/scripts/validation.py", line 113, in validate
    validate_nodes(data)
  File "/Users/dalekurt/Workspaces/cluster-template/bootstrap/scripts/validation.py", line 21, in wrapper
    return func(*[data[key] for key in keys], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dalekurt/Workspaces/cluster-template/bootstrap/scripts/validation.py", line 100, in validate_nodes
    validate_node(node, node_cidr)
  File "/Users/dalekurt/Workspaces/cluster-template/bootstrap/scripts/validation.py", line 71, in validate_node
    raise ValueError(f"Node {node.get('name')} port 50000 is not open")
ValueError: Node control-plane port 50000 is not open
task: Failed to run task "configure": exit status 1
```

### Steps to Reproduce:

1. Run the `task configure` command.

2. Respond with "y" to the prompt about overwriting configurations in the Kubernetes directory.

3. Observe the following error in the output:

```
Traceback (most recent call last):
  ...
  ValueError: Node control-plane port 50000 is not open
```

### Expected Behavior:

The task configure command should either:

* Successfully render the templates without performing this specific node validation, or
* Provide a more informative message or option to skip this validation if it is not critical to the template rendering process.

### Actual Behavior:

The validation script attempts to connect to port 50000 on the node `control-plane` as part of the validation process, and the process fails because the port is not open or the node is not accessible.

**Comment by onedr0p** [comment]
The check is there to make sure the nodes are ready to be bootstrapped, if you have other needs you can comment out the check in the python validation script.

**Comment by dalekurt** [comment]
@onedr0p I understand. I'm currently adding a few additional tasks a packer validate and build, as wells as a terraform plan and apply for Proxmox. I have template for my variable files which should be rendered. However, I will have to make some updates on when and how that is done. 

Thank you
